---
- name: Set the RabbitMQ configuration file
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    owner: root
    group: root
    mode: 0644
  notify: "Restart RabbitMQ"

- name: Set the RabbitMQ defaults file
  template:
    src: default/rabbitmq-server.j2
    dest: /etc/default/rabbitmq-server
    owner: root
    group: root
    mode: 0644
  notify: "Restart RabbitMQ"

- name: Set the RabbitMQ logrotate file
  template:
    src: logrotate/rabbitmq-server.j2
    dest: /etc/logrotate.d/rabbitmq-server
    owner: root
    group: root
    mode: 0644
