---
- name: Install latest version of RabbitMQ
  apt:
    name: rabbitmq-server
    state: "{{ rabbitmq_server_state }}"
    purge: "{{ rabbitmq_server_purge }}"
  when:
    - rabbitmq_version == "latest"

- name: Install specific version of RabbitMQ
  apt:
    name: "rabbitmq-server={{ rabbitmq_version }}"
    state: "{{ rabbitmq_server_state }}"
    purge: "{{ rabbitmq_server_purge }}"
  when:
    - rabbitmq_version != "latest"

- name: Install the Erlang hipe package to use hipe_compile
  apt:
    name: erlang-base-hipe
    state: "{{ rabbitmq_server_state }}"
    purge: "{{ rabbitmq_server_purge }}"
